import type { OcrProvider } from "./ocr-provider";
import { ocrResultSchema, type OcrAvailability, type OcrInput, type OcrMode, type OcrProviderName, type OcrResult } from "./ocr-types";

export class StaticOcrProvider implements OcrProvider {
  readonly name: OcrProviderName;
  private readonly mode: OcrMode;
  private readonly rawText: string;

  constructor(params: { name: OcrProviderName; mode: OcrMode; rawText: string }) {
    this.name = params.name;
    this.mode = params.mode;
    this.rawText = params.rawText;
  }

  async checkAvailability(): Promise<OcrAvailability> {
    return { available: true };
  }

  async recognize(input: OcrInput): Promise<OcrResult> {
    void input;
    return ocrResultSchema.parse({
      provider: this.name,
      rawText: this.rawText,
      blocks: [
        {
          text: this.rawText,
          confidence: null,
          metadata: {},
        },
      ],
      lines: [
        {
          text: this.rawText,
          confidence: null,
          metadata: {},
        },
      ],
      confidence: null,
      warnings: ["This result was generated by a test-only OCR provider."],
      metadata: {
        mode: this.mode,
        processedAt: new Date(0).toISOString(),
        rawProvider: "static",
      },
    });
  }
}
